Pip 1
PolymathNetwork/polymath-core-deprecated pull request #126
Opened 2018-02-02 20:05 UTC by pabloruiz55

2018-02-02 21:08 UTC, adamdossa submitted a review, later dismissed

2018-02-02 21:35 UTC, ChainSafeSystems approved these changes

2018-02-02 21:39 UTC, ChainSafeSystems submitted a review, later dismissed
Chris H likes it =)

2018-02-03 08:03 UTC, satyamakgec commented on PIPs/PIPS/pip-1.md
> +Each PIP parts are explained in pip-X.md template file.
[pip-X.md](../pip-X.md)

2018-02-03 08:03 UTC, satyamakgec requested changes
[pip-X.md](../pip-X.md)

2018-02-04 11:25 UTC, pabloruiz55 commented
@satyamakgec added pip-x.md link

2018-02-04 14:07 UTC, satyamakgec approved these changes

2018-02-04 14:07 UTC, merged