fix #72
PolymathNetwork/polymath-core-deprecated pull request #90
Opened 2018-01-24 07:05 UTC by satyamakgec

`var (totalSupply, owner,,) = STRegistrar.getSecurityTokenData(_securityToken);`
`require(totalSupply > 0 && owner != address(0)); `
 Here I want to use ticker only for comparison but ticker is string type and solidity has not allowed to use dynamically sized variable from return statement. So i go for totalSupply and owner.

2018-01-24 10:11 UTC, adamdossa commented
You can compare strings, by comparing the hash of the strings - something like:
function compareStrings (string a, string b) view returns (bool) {
  return keccak256(a) == keccak256(b);
}

2018-01-24 10:17 UTC, satyamakgec commented
@adamdossa yes I know but the problem in accessing the string, solidity restrict to return the dynamic sized value as bytes, string in another contract i.e I use totalSupply and owner

2018-01-24 15:50 UTC, satyamakgec commented
Done as suggested

2018-01-24 18:59 UTC, pabloruiz55 commented on contracts/Compliance.sol
> +        var (totalSupply, owner,,) = STRegistrar.getSecurityTokenData(_securityToken);
Can you, instead of calling this function from STRegistrar, get a hold of the SecurityToken contract by using its address and read the string?

2018-01-24 19:00 UTC, pabloruiz55 requested changes
Can you, instead of calling getSecurityTokenData from STRegistrar, get a hold of the SecurityToken contract by using its address and read the string?

2018-01-25 04:37 UTC, satyamakgec commented on contracts/Compliance.sol
> +        var (totalSupply, owner,,) = STRegistrar.getSecurityTokenData(_securityToken);
yes, we can do it but the motive of calling the `getSecurityTokenData()` is to verify that provided securityToken is generated by the STR only. If we get the string from the contract address then we can't achieve our motive.

2018-01-25 14:56 UTC, Everhusk commented
@satyamakgec looks good to me, can you fix merge conflicts though.

2018-01-25 15:22 UTC, satyamakgec commented
@Everhusk @pabloruiz55 Please approve it now

2018-01-25 17:05 UTC, satyamakgec commented
@Everhusk please review it now

2018-01-25 17:27 UTC, sangheraio approved these changes

2018-01-25 17:28 UTC, merged